name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
   steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
  with:
    node-version: 18
        - run: npm install hexo-cli -g
        - run: npm install
        - run: hexo generate
        - uses: actions/upload-pages-artifact@v1.0.7
          with:
            # Artifact name
            # Path of the directory containing the static assets.
            path: public/
          - uses: actions/deploy-pages@v1.2.4